WebUI/Models/CartIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class CartIndexViewModel
    {
        public Domain.Entities.Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

WebUI/Models/GameListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class GameListViewModel
    {
        public IEnumerable<Domain.Entities.Game> Games { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentCategory { get; set; }
    }
}

WebUI/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class LoginViewModel
    {
        [Required]
        public string UserName { get; set; }
        [Required]
        public string Password { get; set; }
    }
}

WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages
        {
            get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }
    }
}

WebUI/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Infrastructure.Abstract;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class AccountController : Controller
    {
        IAuthProvider authProvider;
        public AccountController(IAuthProvider auth)
        {
            authProvider = auth;
        }
        public ViewResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                if (authProvider.Authenticate(model.UserName, model.Password))
                {
                    return Redirect(returnUrl ?? Url.Action("Index", "Admin"));
                }
                else
                {
                    ModelState.AddModelError("", "Неправильный логин или пароль");
                    return View();
                }
            }
            else
                return View();
        }
    }
}

WebUI/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;

namespace WebUI.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        IGameRepository repository;
        
        public AdminController(IGameRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index()
        {
            return View(repository.Games);
        }
        
       public ViewResult Edit(int gameId)
        {
            Domain.Entities.Game game = repository.Games
                .FirstOrDefault(x=>x.GameId == gameId);
            return View(game);
        }

        public ViewResult Create()
        {
            return View("Edit", new Domain.Entities.Game());
        }

        // Перегруженная версия
        [HttpPost]
        public ActionResult Edit(Domain.Entities.Game game)
        {
            if (ModelState.IsValid)
            {
                repository.SaveGame(game);
                TempData["message"] = string.Format("Изменение в игре \"{0}\" были сохранены",
                    game.Name);
                return RedirectToAction("Index");
            }
            else
                return View(game);
        }
        [HttpPost]
        public ActionResult Delete (int gameId)
        {
            Domain.Entities.Game delGame = repository.DeleteGame(gameId);
            if (delGame != null)
            {
                TempData["message"] = string.Format("Игра \"{0}\" была удалена",
                    delGame.Name);
            }
            return RedirectToAction("Index");
        }
    }
}

WebUI/Controllers/CartController.cs
using Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Entities;

namespace WebUI.Controllers
{
    public class CartController : Controller
    {
       

        private IGameRepository repository;
        private IOrderProcessor orderProcessor;

        public CartController(IGameRepository repo, IOrderProcessor processor)
        {
            repository = repo;
            orderProcessor = processor;
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new Models.CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.LineCollection.Count() == 0)
                ModelState.AddModelError("", "Корзина пуста");
            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else return View(shippingDetails);
        }


        public RedirectToRouteResult AddToCart(Cart cart, int gameId,string returnUrl)
        {
            Game game = repository.Games
                .FirstOrDefault(x => x.GameId == gameId);

            if (game != null)
                cart.AddItem(game, 1);
            return RedirectToAction("Index",new {returnUrl});
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart,int gameId, string returnUrl)
        {
            Game game = repository.Games
                .FirstOrDefault(x => x.GameId == gameId);
            if (game != null)
                cart.RemoveLine(game);
            return RedirectToAction("Index",new {returnUrl});
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

    }
}

WebUI/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class GameController : Controller
    {
        private Domain.Abstract.IGameRepository repository;
        public int pageSize = 4;
        public GameController(Domain.Abstract.IGameRepository repo)
        {
            repository = repo;
        }
        public ViewResult List(string category, int page = 1)
        {
            WebUI.Models.GameListViewModel model = new WebUI.Models.GameListViewModel
            {
                Games = repository.Games
                .Where(x=> category == null || x.Category == category)
                .OrderBy(x => x.GameId)
                .Skip((page - 1) * pageSize)
                .Take(pageSize),
                PagingInfo = new Models.PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category == null ? 
                    repository.Games.Count() :
                    repository.Games.Where(x=>x.Category == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }
    }
}

WebUI/Controllers/NavController.cs
using Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class NavController : Controller
    {
       private IGameRepository repository;

        public NavController(IGameRepository repo)
        {
            repository = repo;
        }
        public PartialViewResult Menu(string category = null,bool horizontalNav = false)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = repository.Games
                 .Select(x => x.Category)
                 .Distinct()
                 .OrderBy(x => x);

            return PartialView("FlexMenu", categories);
        }
    }
}

WebUI/Views/Admin/Edit.cshtml
@model Domain.Entities.Game

@{
    ViewBag.Title = "Админ панель редактирование товара";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel">
    <div class="panel-heading">
        <h3>Редактирование игры «@Model.Name»</h3>
    </div>

    @using (Html.BeginForm("Edit","Admin"))
    {
        <div class="panel-body">
           
            @Html.HiddenFor(m => m.GameId)
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                if (property.PropertyName != "GameId")
                {
                    <div class="form-group">
                        <label>@(property.DisplayName ?? property.PropertyName)</label>
                        @if (property.PropertyName == "Description")
                        {
                            @Html.TextArea(property.PropertyName, null,
                                new { @class = "form-control", rows = 5 })
                        }
                        else
                        {
                            @Html.TextBox(property.PropertyName, null,
                                new { @class = "form-control" })
                        }
                    </div>
                }
            }
        </div>
        <div class="panel-footer">
            <input type="submit" value="Сохранить" class="btn btn-primary" />
            @Html.ActionLink("Отменить изменения и вернуться к списку", "Index", null, new
            {
                @class = "btn btn-default"
            })
        </div>
    }

   
</div>

WebUI/Views/Admin/Index.cshtml
@model IEnumerable<Domain.Entities.Game>

@{
    ViewBag.Title = "Админ панель: список товаров";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Список игр</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-right">ID</th>
                <th>Название</th>
                <th class="text-right">Цена</th>
                <th class="text-center">Действия</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-right">
                        @item.GameId
                    </td>
                    <td>@Html.ActionLink(item.Name,"Edit", new {item.GameId})</td>
                    <td class="text-right">@item.Price.ToString("# руб")</td>
                    <td class="text-center">
                        @using (Html.BeginForm("Delete","Admin"))
                {
                    @Html.Hidden("GameId", item.GameId)
                            <input 
                                   type="submit"
                                   class="btn btn-default btn-xs" 
                                   value="Удалить"
                                   />
                }
                    </td>
                </tr>
            }
        </table>
        <div class="panel-footer">
            @Html.ActionLink("Добавить игру","Create", null ,
           new {@class = "btn btn-default"})
        </div>
    </div>
</div>

WebUI/Views/Cart/Checkout.cshtml
@model Domain.Entities.ShippingDetails

@{
    ViewBag.Title = "GameStore: форма заказа";
}

<h2>
    Оформить заказ сейчас
</h2>

<p>Пожалуйста введи свои контактные данные</p>

@using (Html.BeginForm())
{
    <h3>Данные</h3>
    <div class="form-group">
        <label>Ваше имя:</label>
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    </div>

    <h3>Адрес доставки</h3>
    foreach (var property in ViewData.ModelMetadata.Properties)
    {
        if (property.PropertyName != "Name" && property.PropertyName != "GiftWrap")
        {
            <div class="form-group">
                <label>@(property.DisplayName ?? property.PropertyName)</label>
                @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
            </div>
        }
    }


    <h3>Опции</h3>
    <div class="checkbox">
        <label>
            @Html.EditorFor(x => x.GiftWrap)
            Использовать подарочную упаковку?
        </label>
    </div>

    <div class="text-center">
        <input class="btn btn-primary" type="submit" value="Обработать заказ" />
    </div>
}

WebUI/Views/Cart/Completed.cshtml
@{
    ViewBag.Title = "Заказ обработан";
}

<h2>Спасибо!</h2>
<p>Спасибо за выбор нашего магазина. Заказ в кратчайшие сроки будет отправлен в службу доставки.</p>

WebUI/Views/Cart/Index.cshtml
@model WebUI.Models.CartIndexViewModel 


@{ 
    ViewBag.Title = "GameStore корзина";
}

<style>
    #cartTable td {vertical-align:middle;}
</style>

<h2>Ваша корзина</h2>
<table id="cartTable" class="table">
    <thead>
        <tr>
            <th>Кол-во</th>
            <th>Игра</th>
            <th class="text-right">Цена</th>
            <th  class="text-right">Общая цена</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.LineCollection)
            {
                <tr>
                    <td class="text-center">@line.Quantity</td>
                    <td class="text-left">@line.Game.Name</td>
                    <td class="text-right">@line.Game.Price.ToString("# руб")</td>
                    <td class="text-right">
                        @((line.Quantity * line.Game.Price).ToString("# руб"))
                    </td>
                    <td>
                        @using (Html.BeginForm("RemoveFromCart","Cart"))
                         {
                            @Html.Hidden("GameId", line.Game.GameId)
                            @Html.HiddenFor(x=>x.ReturnUrl)
                            <input class="btn btn-sm btn-warning" type="submit" value="Удалить"/>
                         }
                    </td>
                </tr>
            }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Итого:</td>
            <td class="text-right">
                @Model.Cart.ComputeTotalValue().ToString("# руб")
            </td>
        </tr>
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Продолжить покупки</a>
    @Html.ActionLink("Оформить заказ","Checkout", null, new {@class = "btn btn-primary"})
</div>

WebUI/Views/Cart/Summary.cshtml
@model Domain.Entities.Cart

<div class="navbar-right hidden-xs">
    @Html.ActionLink("Заказать","Index","Cart",
    new {returnUrl = Request.Url.PathAndQuery},
    new {@class = "btn btn-default navbar-btn"}
    )
</div>

<div class="navbar-right hidden-xs">
    <a href="@Url.Action("Index","Cart", 
            new {returnUrl = Request.Url.PathAndQuery})"
       class="btn btn-default navbar-btn">
        <span class="glyphicon glyphicon-shopping-cart"/>
    </a>
</div>

<div class="navbar-text navbar-right">
    <b class="hidden-xs">Ваша корзина</b>
    @Model.LineCollection.Sum(x=>x.Quantity) игр,
    @Model.ComputeTotalValue().ToString("# руб")
</div>

WebUI/Views/Game/List.cshtml
@using WebUI.HtmlHelpers
@using WebUI.Models
@model GameListViewModel

@{
    ViewBag.Title = "Товары";
}

@foreach (var x in @Model.Games)
            {
                @Html.Partial("GameSummary" , x)
            }

<div class="btn-group-justified pull-right">
    @Html.PageLinks(Model.PagingInfo,x=> Url.Action
("List", new {page = x, category = Model.CurrentCategory})
)
</div>

WebUI/Views/Nav/FlexMenu.cshtml
@model IEnumerable<string>

@{ 
    bool horizontal = ((bool)(ViewContext.RouteData.Values["horizontalNav"] ?? false));
    string wrapperClass = horizontal ? "btn-group btn-group-sm btn-group-justified" : null;

}

<div class="@wrapperClass">
    @Html.ActionLink("Домой","List","Game", null,
    new
    {
        @class = horizontal ? "btn btn-default btn-sm" :
            "btn btn-block btn-default btn-lg"
    })

    @foreach (var link in Model)
            {
                @Html.RouteLink(link,new
           {
               controller = "Game",
               action = "List",
               category = link,
               page = 1
           }, new
           {
               @class = (horizontal ? "btn btn-default btn-sm" 
               : "btn btn-block btn-default btn-lg") 
               + (link == ViewBag.SelectedCategory ? " btn-primary" : "")
           }
           )
            }
</div>

WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@Html.ActionLink("Домой!", "List", "Game",null,
    new {@class = "btn btn-block btn-default btn-lg" }
    )

@foreach (var link in Model)
            {
                @Html.RouteLink(link, new
           {
               controller = "Game",
               action = "List",
               category = link,
               page = 1
           },
           new
           {
               @class = "btn btn-block btn-default btn-lg" +
           (link == ViewBag.SelectedCategory ? " btn-primary" : "")
           }
           )
            }

WebUI/Views/Nav/MenuHorizontal.cshtml
@model IEnumerable<string>

<div class="btn-group btn-group-sm btn-group-justified">
    @Html.ActionLink("Домой", "List", "Game", null,
    new {@class = "btn btn-default btn-sm"}
    )

    @foreach (var link in Model)
            {
                @Html.RouteLink(link, new
           {
               controller = "Game",
               action = "List",
               category = link,
               page = 1
           }, new
           {
               @class = "btn btn-default btn-sm"
               + (link == ViewBag.SelectedCategory ? " btn-primary" : "")
           }
           )
            }
</div>

WebUI/Views/Shared/GameSummary.cshtml
@model Domain.Entities.Game

<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("# руб")</span>
    </h3>
    @using (Html.BeginForm("AddToCart","Cart"))
            {
                <div class="pull-right">
                    @Html.HiddenFor(x=>x.GameId)
                    @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                    <input type="submit" class="btn btn-success" value="Добавить в корзину" />
                </div>
            }

    <span class="lead">@Model.Description</span>
</div>

WebUI/Views/Shared/Mobile.cshtml
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"
          href="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.css" />
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div data-role="page" id="page1">
        <div data-theme="a" data-role="header" data-position="fixed">
            <h3>GameStore</h3>
            @Html.Action("Menu", "Nav")
        </div>
        <div data-role="content">
            <ul data-role="listview" data-divider-theme="b" data-inset="false">
                @RenderBody()
            </ul>
        </div>
    </div>
</body>
</html>

WebUI/Views/Shared/_AdminLayout.cshtml
@{ 
    Layout = null;
}

<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <link href="~/Content/bootstrap.css" rel="stylesheet"/>
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet"/>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
            @RenderBody()
    </div>
</body>
</html>

WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
    <style>
        .navbar-right{
            float: right !important;
            margin-left:15px;
            margin-right:15px;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">
            <span class="hidden-xs">GameStore - магазин пк игр</span>
            <div class="visible-xs">Game</div>
            <div class="visible-xs">Store</div>
        </a>
        @Html.Action("Summary","Cart")
    </div>

    <div class="visible-xs">
        @Html.Action("Menu","Nav",new {horizontalNav = true})
    </div>

    <div class="row panel">
        <div id="categories" class="col-sm-3 hidden-xs">
            @Html.Action("Menu","Nav")
        </div>
        <div class="col-xs-12 col-sm-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>